name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build test image
        run: docker build --target test -t myapp:test .

      - name: Create network
        run: docker network create test-net || true

      - name: Run PostgreSQL container
        run: |
          docker run -d --rm --name test-postgres --network test-net \
            -e POSTGRES_USER=kubsu -e POSTGRES_PASSWORD=kubsu -e POSTGRES_DB=kubsu \
            postgres:15

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            docker exec test-postgres pg_isready -U kubsu && break || sleep 3;
          done

      - name: Run tests inside built image
        env:
          DATABASE_URL: postgresql+psycopg://kubsu:kubsu@test-postgres:5432/kubsu
        run: |
          docker run --rm --network test-net -e DATABASE_URL myapp:test

      - name: Stop Postgres container
        run: docker stop test-postgres

      - name: Build final image
        run: docker build -t myapp:latest .

      - name: Push final image
        run: docker push myapp:latest

      - name: Deploy to server
        if: success()
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            docker pull myapp:latest
            docker stop app01 || true
            docker rm app01 || true
            docker run -d --name app01 -p 8086:8086 myapp:latest

