name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test image
        working-directory: ./docker
        run: |
          podman build --target builder -t myapp:test .

      - name: Run tests
        working-directory: ./docker
        run: |
          podman run --rm myapp:test sh -c "pip install pytest && pytest"

      - name: Build production image
        working-directory: ./docker
        run: |
          podman build -t myapp:latest .

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            podman stop app01 || true
            podman rm app01 || true
            podman run -d \
              --net=host \
              --name app01 \
              -p 60080:60080 \
              myapp:latest
