name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test SSH connection
        uses: glebarez/ssh@main
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          command: echo "SSH connection successful"

      - name: Build images
        working-directory: ./docker
        run: |
          podman build --target builder -t myapp:test .
          podman build -t myapp:latest .

      - name: Run tests on server
        uses: glebarez/ssh@main
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          command: |
            podman run --net=host --rm myapp:test sh -c "pip install pytest && pytest"

      - name: Deploy to server
        uses: glebarez/ssh@main
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          privateKey: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          command: |
            podman stop app01 || true
            podman rm app01 || true
            podman run -d \
              --net=host \
              --name app01 \
              -p 8086:8086 \
              myapp:latest
