name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build images
        working-directory: ./docker
        run: |
          podman build --target builder -t myapp:test .
          podman build -t myapp:latest .

      - name: Run tests on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            podman save myapp:test | podman load
            podman run --rm \
              --net=host \
              -e DATABASE_URL="${{ secrets.TEST_DATABASE_URL }}" \
              myapp:test \
              sh -c "pip install pytest && pytest"

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            podman stop app01 || true
            podman rm app01 || true
            podman run -d \
              --net=host \
              --name app01 \
              -p 8086:8086 \
              myapp:latest
