name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Podman
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Build and test
        working-directory: ./docker
        run: |
          podman build --target builder -t myapp:test .
          podman run --rm myapp:test pytest tests/

      - name: Build final image
        working-directory: ./docker
        run: podman build -t myapp:latest .

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            podman stop app01 || true
            podman rm app01 || true
            podman run -d --net=host --name app01 -p 8086:8086 myapp:latest
